/****** Object:  Table [dbo].[CHAT]    Script Date: 29/04/2025 12:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHAT](
	[ID_MENSAJE] [int] NOT NULL,
	[ID_USUARIO_REMITENTE] [int] NOT NULL,
	[ID_USUARIO_DESTINATARIO] [int] NOT NULL,
	[MENSAJE] [nvarchar](max) NOT NULL,
	[FECHA_ENVIO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_MENSAJE] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMENTARIOS]    Script Date: 29/04/2025 12:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMENTARIOS](
	[ID_COMENTARIO] [int] NOT NULL,
	[ID_LUGAR] [int] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[COMENTARIO] [nvarchar](max) NOT NULL,
	[FECHA_COMENTARIO] [datetime] NOT NULL,
	[NOMBRE_USUARIO] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_COMENTARIO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOG_IN]    Script Date: 29/04/2025 12:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOG_IN](
	[ID_USUARIO] [int] NOT NULL,
	[CORREO] [nvarchar](255) NOT NULL,
	[CLAVE] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CORREO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LUGARES]    Script Date: 29/04/2025 12:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LUGARES](
	[ID_LUGAR] [int] NOT NULL,
	[NOMBRE] [nvarchar](255) NOT NULL,
	[DESCRIPCION] [nvarchar](max) NOT NULL,
	[UBICACION] [nvarchar](255) NOT NULL,
	[CATEGORIA] [nvarchar](255) NOT NULL,
	[HORARIO] [datetime] NOT NULL,
	[IMAGEN] [nvarchar](255) NOT NULL,
	[TIPO] [nvarchar](50) NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_LUGAR] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LUGARESFAVORITOS]    Script Date: 29/04/2025 12:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LUGARESFAVORITOS](
	[ID_FAVORITO] [int] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[ID_LUGAR] [int] NOT NULL,
	[FECHADEVISITA_LUGAR] [date] NOT NULL,
	[IMAGEN_LUGAR] [nvarchar](255) NOT NULL,
	[NOMBRE_LUGAR] [nvarchar](255) NOT NULL,
	[DESCRIPCION_LUGAR] [nvarchar](max) NOT NULL,
	[UBICACION_LUGAR] [nvarchar](255) NOT NULL,
	[TIPO_LUGAR] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_FAVORITO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SEGUIDORES]    Script Date: 29/04/2025 12:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SEGUIDORES](
	[ID_SEGUIDOR] [int] NOT NULL,
	[ID_USUARIO_SEGUIDOR] [int] NOT NULL,
	[ID_USUARIO_SEGUIDO] [int] NOT NULL,
	[FECHA_SEGUIMIENTO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_SEGUIDOR] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIOS]    Script Date: 29/04/2025 12:59:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[ID_USUARIO] [int] NOT NULL,
	[EMAIL] [nvarchar](255) NOT NULL,
	[NOMBRE] [nvarchar](255) NOT NULL,
	[EDAD] [int] NOT NULL,
	[NACIONALIDAD] [nvarchar](100) NOT NULL,
	[CLAVE] [nvarchar](255) NOT NULL,
	[CONFIRMARCLAVE] [nvarchar](255) NOT NULL,
	[PREFERENCIASDEVIAJE] [nvarchar](max) NOT NULL,
	[AVATARURL] [nvarchar](255) NOT NULL,
	[FECHADEREGISTRO] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[EMAIL] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHAT]  WITH CHECK ADD FOREIGN KEY([ID_USUARIO_REMITENTE])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[CHAT]  WITH CHECK ADD FOREIGN KEY([ID_USUARIO_DESTINATARIO])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[COMENTARIOS]  WITH CHECK ADD FOREIGN KEY([ID_LUGAR])
REFERENCES [dbo].[LUGARES] ([ID_LUGAR])
GO
ALTER TABLE [dbo].[COMENTARIOS]  WITH CHECK ADD FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[LOG_IN]  WITH CHECK ADD FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[LUGARES]  WITH CHECK ADD  CONSTRAINT [FK_LUGARES_USUARIOS] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[LUGARES] CHECK CONSTRAINT [FK_LUGARES_USUARIOS]
GO
ALTER TABLE [dbo].[LUGARESFAVORITOS]  WITH CHECK ADD FOREIGN KEY([ID_LUGAR])
REFERENCES [dbo].[LUGARES] ([ID_LUGAR])
GO
ALTER TABLE [dbo].[LUGARESFAVORITOS]  WITH CHECK ADD FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[SEGUIDORES]  WITH CHECK ADD  CONSTRAINT [FK_SEGUIDORES_SEGUIDO] FOREIGN KEY([ID_USUARIO_SEGUIDO])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO
ALTER TABLE [dbo].[SEGUIDORES] CHECK CONSTRAINT [FK_SEGUIDORES_SEGUIDO]
GO


